server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/jwt_app_db
    driver-class-name: org.postgresql.Driver
    username: jwt_user
    password: very_secret_password
