server:
  port: 5000
spring:
  datasource:
    url: jdbc:mysql://172.17.0.4:3306/jwt_app_db?serverTimezone=UTC&&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


